Program extract_pot
  !-----------------------------------------------------------------------
  ! Extract BOTH supercell KS potentials (defect + pristine) on-the-fly
  ! and write them to Gaussian cube files. Runs as a SERIAL program (1 MPI rank)
  ! to avoid the MPI_COMM_SELF state corruption in edi.x.
  !
  ! Calls read_file_new twice in sequence — this works correctly on a
  ! single rank (same as edi_test_pot.x / pp.x).
  !
  ! Usage:
  !   srun -n 1 extract_pot.x -i extract_pot.in
  !
  ! Input:
  !   &extract_pot_nml
  !     defect_prefix  = 'mos2_defect'
  !     defect_outdir  = '../defect_super/dout/'
  !     pristine_prefix = 'mos2_pristine'
  !     pristine_outdir = '../pristine_super/dout/'
  !     potfile_d = 'V_d.cube'
  !     potfile_p = 'V_p.cube'
  !   /
  !
  ! Output: two cube files (V_d.cube, V_p.cube) for comparison with pp.x
  !   and for use by edi.x via load_pot_from_file().
  !-----------------------------------------------------------------------
  USE kinds, ONLY : dp
  USE io_files, ONLY : prefix, tmp_dir
  USE scf, ONLY : v, vltot
  USE fft_base, ONLY : dfftp
  USE ions_base, ONLY : nat, ntyp => nsp, ityp, tau
  USE cell_base, ONLY : at, alat, celldm, ibrav, omega
  USE environment, ONLY : environment_start, environment_end
  USE mp_global, ONLY : mp_startup, mp_global_end
  USE io_global, ONLY : stdout

  IMPLICIT NONE

  CHARACTER(LEN=256), EXTERNAL :: trimcheck
  CHARACTER(LEN=256) :: defect_prefix, defect_outdir
  CHARACTER(LEN=256) :: pristine_prefix, pristine_outdir
  CHARACTER(LEN=256) :: potfile_d, potfile_p
  LOGICAL :: wfc_is_collected
  INTEGER :: ios

  NAMELIST /extract_pot_nml/ defect_prefix, defect_outdir, &
       pristine_prefix, pristine_outdir, potfile_d, potfile_p

  CALL mp_startup(start_images=.TRUE.)
  CALL environment_start('EXTRACT_POT')

  ! Defaults
  defect_prefix = ' '
  defect_outdir = './'
  pristine_prefix = ' '
  pristine_outdir = './'
  potfile_d = 'V_d.cube'
  potfile_p = 'V_p.cube'

  CALL input_from_file()
  READ(5, NML=extract_pot_nml, IOSTAT=ios)
  IF (ios < 0) ios = 0
  IF (ios > 0) THEN
     WRITE(stdout,*) 'Error reading extract_pot_nml namelist'
     STOP 1
  ENDIF

  WRITE(stdout, '(/,5X,A)') REPEAT('=', 60)
  WRITE(stdout, '(5X,A)')   'Supercell potential extraction'
  WRITE(stdout, '(5X,A)')   REPEAT('=', 60)

  ! ============================================================
  ! Extract defect supercell potential
  ! ============================================================
  WRITE(stdout, '(/,5X,A,A)') 'Defect prefix:   ', TRIM(defect_prefix)
  WRITE(stdout, '(5X,A,A)')   'Defect outdir:   ', TRIM(defect_outdir)

  CALL clean_pw(.TRUE.)
  prefix = TRIM(defect_prefix)
  tmp_dir = trimcheck(TRIM(defect_outdir))
  wfc_is_collected = .FALSE.
  CALL read_file_new(wfc_is_collected)

  CALL write_pot_cube(potfile_d)

  ! ============================================================
  ! Extract pristine supercell potential
  ! ============================================================
  WRITE(stdout, '(/,5X,A,A)') 'Pristine prefix: ', TRIM(pristine_prefix)
  WRITE(stdout, '(5X,A,A)')   'Pristine outdir: ', TRIM(pristine_outdir)

  CALL clean_pw(.TRUE.)
  prefix = TRIM(pristine_prefix)
  tmp_dir = trimcheck(TRIM(pristine_outdir))
  wfc_is_collected = .FALSE.
  CALL read_file_new(wfc_is_collected)

  CALL write_pot_cube(potfile_p)

  WRITE(stdout, '(/,5X,A)') REPEAT('=', 60)
  WRITE(stdout, '(5X,A)')   'Done.'
  WRITE(stdout, '(5X,A)')   REPEAT('=', 60)

  CALL environment_end('EXTRACT_POT')
  CALL mp_global_end()

CONTAINS

  SUBROUTINE write_pot_cube(fname)
    CHARACTER(LEN=*), INTENT(IN) :: fname
    INTEGER :: iunit, ia, irx, iry, irz, inr, nval
    REAL(dp) :: voxel(3)

    WRITE(stdout, '(5X,A,3I6)') '  FFT grid: ', dfftp%nr1, dfftp%nr2, dfftp%nr3
    WRITE(stdout, '(5X,A,3I6)') '  padded:   ', dfftp%nr1x, dfftp%nr2x, dfftp%nr3x
    WRITE(stdout, '(5X,A,I12)') '  nnr     = ', dfftp%nnr
    WRITE(stdout, '(5X,A,I6)')  '  nat     = ', nat
    WRITE(stdout, '(5X,A,2ES14.6)') '  V_Hxc   min/max = ', &
         MINVAL(v%of_r(1:dfftp%nnr,1)), MAXVAL(v%of_r(1:dfftp%nnr,1))
    WRITE(stdout, '(5X,A,2ES14.6)') '  V_ionic min/max = ', &
         MINVAL(vltot(1:dfftp%nnr)), MAXVAL(vltot(1:dfftp%nnr))
    WRITE(stdout, '(5X,A,2ES14.6)') '  V_total min/max = ', &
         MINVAL(v%of_r(1:dfftp%nnr,1) + vltot(1:dfftp%nnr)), &
         MAXVAL(v%of_r(1:dfftp%nnr,1) + vltot(1:dfftp%nnr))

    iunit = 99
    OPEN(iunit, FILE=TRIM(fname), STATUS='replace', ACTION='write')

    WRITE(iunit, '(A,A,A)') 'V_total = V_Hxc + V_ionic [Ry] (', TRIM(prefix), ')'
    WRITE(iunit, '(A)') 'Generated by extract_pot.x'

    WRITE(iunit, '(I5, 3F12.6)') nat, 0.0_dp, 0.0_dp, 0.0_dp
    voxel(:) = at(:,1) * alat / DBLE(dfftp%nr1)
    WRITE(iunit, '(I5, 3F12.6)') dfftp%nr1, voxel
    voxel(:) = at(:,2) * alat / DBLE(dfftp%nr2)
    WRITE(iunit, '(I5, 3F12.6)') dfftp%nr2, voxel
    voxel(:) = at(:,3) * alat / DBLE(dfftp%nr3)
    WRITE(iunit, '(I5, 3F12.6)') dfftp%nr3, voxel

    DO ia = 1, nat
       WRITE(iunit, '(I5, 4F12.6)') ityp(ia), 0.0_dp, &
            tau(1,ia)*alat, tau(2,ia)*alat, tau(3,ia)*alat
    ENDDO

    ! Cube format: x outermost, z innermost
    ! Use nr1x stride to access QE's real-space array correctly
    DO irx = 0, dfftp%nr1 - 1
       DO iry = 0, dfftp%nr2 - 1
          nval = 0
          DO irz = 0, dfftp%nr3 - 1
             inr = irx + iry * dfftp%nr1x + irz * dfftp%nr1x * dfftp%nr2x + 1
             WRITE(iunit, '(ES16.8)', ADVANCE='NO') v%of_r(inr,1) + vltot(inr)
             nval = nval + 1
             IF (MOD(nval, 6) == 0) WRITE(iunit, *)
          ENDDO
          IF (MOD(nval, 6) /= 0) WRITE(iunit, *)
       ENDDO
    ENDDO

    CLOSE(iunit)
    WRITE(stdout, '(5X,A,A)') '  Written: ', TRIM(fname)
  END SUBROUTINE

End Program extract_pot
