subroutine get_vloc_onthefly(prefix_in, outdir_in, vf_out, is_noncolin, &
                              bxc_out)
  USE kinds,            ONLY : DP
  USE io_files,         ONLY : prefix, tmp_dir
  USE scf,              ONLY : v, vltot
  USE fft_base,         ONLY : dfftp
  USE ions_base,        ONLY : nat, ntyp => nsp, ityp, tau
  USE cell_base,        ONLY : at, alat, celldm, ibrav, omega
  USE edic_mod,         ONLY : V_file

  IMPLICIT NONE

  CHARACTER(LEN=*), INTENT(IN)  :: prefix_in, outdir_in
  TYPE(V_file), INTENT(INOUT)   :: vf_out
  LOGICAL, INTENT(IN)           :: is_noncolin
  REAL(DP), ALLOCATABLE, INTENT(OUT), OPTIONAL :: bxc_out(:,:)

  CHARACTER(LEN=256), EXTERNAL :: trimcheck
  LOGICAL :: wfc_is_collected

  ! Clean any stale QE state from a previous call before re-initializing.
  ! This must happen in the SAME communicator context as read_file_new
  ! (e.g., both under COMM_SELF) to avoid state corruption.
  CALL clean_pw(.TRUE.)

  prefix = TRIM(prefix_in)
  tmp_dir = trimcheck(outdir_in)

  wfc_is_collected = .false.
  CALL read_file_new(wfc_is_collected)

  vf_out%nr1 = dfftp%nr1
  vf_out%nr2 = dfftp%nr2
  vf_out%nr3 = dfftp%nr3
  vf_out%nr1x = dfftp%nr1x
  vf_out%nr2x = dfftp%nr2x
  vf_out%nr3x = dfftp%nr3x

  ALLOCATE(vf_out%pot(dfftp%nnr))
  vf_out%pot(:) = v%of_r(:,1) + vltot(:)

  vf_out%nat = nat
  vf_out%ntyp = ntyp
  ALLOCATE(vf_out%ityp(nat))
  ALLOCATE(vf_out%tau(3, nat))
  vf_out%ityp(:) = ityp(1:nat)
  vf_out%tau(:,:) = tau(:, 1:nat)

  vf_out%alat = alat
  vf_out%ibrav = ibrav
  vf_out%celldm = celldm
  vf_out%at = at
  vf_out%omega = omega

  IF (is_noncolin .AND. PRESENT(bxc_out)) THEN
    ALLOCATE(bxc_out(dfftp%nnr, 3))
    bxc_out(:,1) = v%of_r(:,2)
    bxc_out(:,2) = v%of_r(:,3)
    bxc_out(:,3) = v%of_r(:,4)
  ENDIF

  ! Write diagnostic cube file for the KS potential
  BLOCK
    INTEGER :: iunit_cube, irx, iry, irz, inr, ia, nval
    REAL(DP) :: voxel(3)
    CHARACTER(LEN=256) :: cubename

    iunit_cube = 97
    cubename = TRIM(prefix) // '_vtot_onthefly.cube'
    OPEN(iunit_cube, FILE=TRIM(cubename), STATUS='REPLACE', ACTION='WRITE')
    WRITE(iunit_cube, '(A,A,A)') 'V_total = V_Hxc + V_ionic [Ry] (', TRIM(prefix), ')'
    WRITE(iunit_cube, '(A)') 'Generated by get_vloc_onthefly'
    WRITE(iunit_cube, '(I5, 3F12.6)') nat, 0.0_DP, 0.0_DP, 0.0_DP
    voxel(:) = at(:,1) * alat / DBLE(dfftp%nr1)
    WRITE(iunit_cube, '(I5, 3F12.6)') dfftp%nr1, voxel
    voxel(:) = at(:,2) * alat / DBLE(dfftp%nr2)
    WRITE(iunit_cube, '(I5, 3F12.6)') dfftp%nr2, voxel
    voxel(:) = at(:,3) * alat / DBLE(dfftp%nr3)
    WRITE(iunit_cube, '(I5, 3F12.6)') dfftp%nr3, voxel
    DO ia = 1, nat
       WRITE(iunit_cube, '(I5, 4F12.6)') ityp(ia), 0.0_DP, &
            tau(1,ia)*alat, tau(2,ia)*alat, tau(3,ia)*alat
    ENDDO
    ! Cube format: x outermost, z innermost
    DO irx = 0, dfftp%nr1 - 1
       DO iry = 0, dfftp%nr2 - 1
          nval = 0
          DO irz = 0, dfftp%nr3 - 1
             inr = irx + iry * dfftp%nr1x + irz * dfftp%nr1x * dfftp%nr2x + 1
             WRITE(iunit_cube, '(ES13.5)', ADVANCE='NO') vf_out%pot(inr)
             nval = nval + 1
             IF (MOD(nval, 6) == 0) WRITE(iunit_cube, *)
          ENDDO
          IF (MOD(nval, 6) /= 0) WRITE(iunit_cube, *)
       ENDDO
    ENDDO
    CLOSE(iunit_cube)
    WRITE(*, '(A,A)') '  Cube file written: ', TRIM(cubename)
  END BLOCK

end subroutine get_vloc_onthefly
