title: EDI software
description: A first principle software that calculates Electron-Defect Interaction.
show_downloads: true
github.is_project_page: true
google_analytics:
theme: jekyll-theme-cayman
