title: EDI software
description: accurately calculate electron-defect interactions from first principles
show_downloads: true
github.is_project_page: true
google_analytics:
theme: jekyll-theme-cayman
plugins:

redirect_from:
  - /edi
